---
openapi: 3.0.1
x-stoplight:
  id: 76mav8ydoatod
info:
  title: nahlun-server
  description: ""
  version: 0.0.1
  license:
    name: MIT
    url: "https://opensource.org/license/mit"
tags:
  - name: tile
  - name: public/river
  - name: public/voxel_model
  - name: public/sensor
  - name: private/sensor
  - name: private/voxel_model
paths:
  "/tiles/water/{z}/{x}/{y}":
    get:
      summary: 水面タイル
      deprecated: false
      description: "deck.glのTerrainLayerに喰わせる。\n水面を表現した標高画像タイルを返す"
      tags:
        - tile
      parameters:
        - name: z
          in: path
          description: ""
          required: true
          schema:
            type: integer
            format: int64
            minimum: 0.0
        - name: x
          in: path
          description: ""
          required: true
          schema:
            type: integer
            format: int64
            minimum: 0.0
        - name: y
          in: path
          description: ""
          required: true
          schema:
            type: integer
            format: int64
            minimum: 0.0
      responses:
        "200":
          description: ""
          content:
            model/gltf-binary:
              schema:
                type: string
                format: binary
          headers:
            Content-Encoding:
              schema:
                type: string
                default: zstd
              description: zstd
      security: [ ]
      operationId: ""
  "/tiles/land/{z}/{x}/{y}":
    get:
      summary: 陸域タイル
      deprecated: false
      description: ボクセルモデルを返し、なければ標高タイルから生成したものにフォールバックする
      tags:
        - tile
      parameters:
        - name: z
          in: path
          description: ""
          required: true
          schema:
            type: integer
            format: int64
            minimum: 0.0
        - name: x
          in: path
          description: ""
          required: true
          schema:
            type: integer
            format: int64
            minimum: 0.0
        - name: y
          in: path
          description: ""
          required: true
          schema:
            type: integer
            format: int64
            minimum: 0.0
      responses:
        "200":
          description: ""
          content:
            model/gltf-binary:
              schema:
                type: string
                format: binary
          headers:
            Content-Encoding:
              schema:
                type: string
                default: zstd
              description: zstd
      security: [ ]
  /api/sensors:
    put:
      summary: 登録/上書き
      deprecated: false
      description: ""
      tags:
        - private/sensor
      parameters:
        - name: id
          in: query
          description: ID番号
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                altitude:
                  type: number
                  format: float
                interval:
                  type: integer
                  minimum: 0.0
                  format: int32
                scope:
                  type: number
                  format: float
                  minimum: 0.0
                parent_node:
                  type: integer
                  x-stoplight:
                    id: o6h62euno1464
                    explicitProperties:
                      - type
                      - format
                      - minimum
                  format: int64
                  minimum: 0.0
              required:
                - altitude
                - interval
                - scope
                - parent_node
      responses:
        "200":
          description: ""
          content: { }
          headers: { }
      security: [ ]
    delete:
      summary: 削除
      deprecated: false
      description: ""
      tags:
        - private/sensor
      parameters:
        - name: id
          in: query
          description: ID番号
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: ""
          content: { }
          headers: { }
      security: [ ]
  /api/sensors/data:
    parameters: [ ]
    post:
      summary: ""
      operationId: post-api-sensors-data
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: integer
                format: int32
      parameters:
        - schema:
            type: string
            format: uuid
          in: query
          name: id
          description: sersor_uuid
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                distance:
                  type: array
                  x-stoplight:
                    id: mhwq74ndz0w04
                  items:
                    x-stoplight:
                      id: hj6atflma2p11
                      explicitProperties:
                        - type
                        - format
                    type: number
                    format: float
                battery_voltage:
                  type: integer
                  x-stoplight:
                    id: 5xqio0w6q42vu
                previous_sleep_time:
                  type: integer
                  x-stoplight:
                    id: my3fclzrir3iy
                network_status:
                  type: string
                  x-stoplight:
                    id: e8wsj4prtgwx6
              required:
                - distance
                - battery_voltage
                - previous_sleep_time
                - network_status
components:
  schemas: { }
  securitySchemes: { }
servers: [ ]
