---
openapi: 3.0.1
info:
  title: nahlun-server
  description: ""
  version: 1.0.0
tags:
  - name: tile
  - name: public
  - name: public/river
  - name: public/voxel_model
  - name: public/sensor
  - name: private
  - name: private/sensor
  - name: private/voxel_model
paths:
  "/tiles/water/{z}/{x}/{y}":
    get:
      summary: 水面タイル
      deprecated: false
      description: "deck.glのTerrainLayerに喰わせる。\n水面を表現した標高画像タイルを返す"
      tags:
        - tile
      parameters:
        - name: z
          in: path
          description: ""
          required: true
          schema:
            type: integer
            format: int64
            minimum: 0.0
        - name: x
          in: path
          description: ""
          required: true
          schema:
            type: integer
            format: int64
            minimum: 0.0
        - name: y
          in: path
          description: ""
          required: true
          schema:
            type: integer
            format: int64
            minimum: 0.0
      responses:
        "200":
          description: ""
          content:
            "*/*":
              schema:
                type: object
                properties: {}
                x-apidog-ignore-properties: []
                x-apidog-orders: []
          headers: {}
          x-apidog-name: 成功
      security: []
      x-apidog-folder: tile
      x-apidog-status: designing
      x-run-in-apidog: "https://app.apidog.com/web/project/663078/apis/api-10004446-run"
  "/tiles/land/{z}/{x}/{y}":
    get:
      summary: 陸域タイル
      deprecated: false
      description: ボクセルモデルを返し、なければ標高タイルから生成したものにフォールバックする
      tags:
        - tile
      parameters:
        - name: z
          in: path
          description: ""
          required: true
          schema:
            type: integer
            format: int64
            minimum: 0.0
        - name: x
          in: path
          description: ""
          required: true
          schema:
            type: integer
            format: int64
            minimum: 0.0
        - name: y
          in: path
          description: ""
          required: true
          schema:
            type: integer
            format: int64
            minimum: 0.0
      responses:
        "200":
          description: ""
          content:
            "*/*":
              schema:
                type: array
                items:
                  type: object
                  properties: {}
                  x-apidog-orders: []
                  x-apidog-ignore-properties: []
          headers: {}
          x-apidog-name: 成功
      security: []
      x-apidog-folder: tile
      x-apidog-status: designing
      x-run-in-apidog: "https://app.apidog.com/web/project/663078/apis/api-10004449-run"
  /api/river-nodes:
    get:
      summary: ノード情報の取得
      deprecated: false
      description: ""
      tags:
        - public/river
      parameters:
        - name: id
          in: query
          description: ID番号
          required: true
          schema:
            type: integer
            format: int64
        - name: relation_limit
          in: query
          description: 繋がりのあるノードをいくつ持ってくるか
          required: false
          schema:
            type: integer
            default: 0
            format: int32
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: array
                items:
                  type: array
                  items:
                    $ref: "#/components/schemas/RiverNode"
                  description: 指定したidから始まるパス
                description: パスの配列
          headers: {}
          x-apidog-name: 成功
      security: []
      x-apidog-folder: public/river
      x-apidog-status: designing
      x-run-in-apidog: "https://app.apidog.com/web/project/663078/apis/api-10013003-run"
  /api/river-nodes/bulk:
    get:
      summary: 範囲内のノードの情報を読む
      deprecated: false
      description: ""
      tags:
        - public/river
      parameters:
        - name: max-longitude
          in: query
          description: ""
          required: true
          schema:
            type: number
            format: double
            minimum: -180.0
            maximum: 180.0
        - name: min-longitude
          in: query
          description: ""
          required: true
          schema:
            type: number
            format: double
            minimum: -180.0
            maximum: 180.0
        - name: max-latitude
          in: query
          description: ""
          required: true
          schema:
            type: number
            format: double
            minimum: -90.0
            maximum: 90.0
        - name: min-latitude
          in: query
          description: ""
          required: true
          schema:
            type: number
            format: double
            minimum: -90.0
            maximum: 90.0
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/RiverNode"
                description: RiverNodeのつながりの集合
          headers: {}
          x-apidog-name: 成功
      security: []
      x-apidog-folder: public/river
      x-apidog-status: designing
      x-run-in-apidog: "https://app.apidog.com/web/project/663078/apis/api-10022275-run"
  /api/voxel-models/bulk:
    get:
      summary: 範囲内のモデルの情報を読む
      deprecated: false
      description: ""
      tags:
        - public/voxel_model
      parameters:
        - name: max-longitude
          in: query
          description: ""
          required: true
          schema:
            type: number
            format: double
        - name: min-longitude
          in: query
          description: ""
          required: true
          schema:
            type: number
            format: double
        - name: max-latitude
          in: query
          description: ""
          required: true
          schema:
            type: number
            format: double
        - name: min-latitude
          in: query
          description: ""
          required: true
          schema:
            type: number
            format: double
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/VoxelModel"
          headers: {}
          x-apidog-name: 成功
      security: []
      x-apidog-folder: public/voxel_model
      x-apidog-status: designing
      x-run-in-apidog: "https://app.apidog.com/web/project/663078/apis/api-10006499-run"
  /api/voxel-models:
    get:
      summary: モデルの取得
      deprecated: false
      description: 指定したidのモデルを取得する
      tags:
        - public/voxel_model
      parameters:
        - name: id
          in: query
          description: ""
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: ""
          content:
            "*/*":
              schema:
                type: object
                properties: {}
                x-apidog-ignore-properties: []
                x-apidog-orders: []
          headers: {}
          x-apidog-name: 成功
      security: []
      x-apidog-folder: public/voxel_model
      x-apidog-status: designing
      x-run-in-apidog: "https://app.apidog.com/web/project/663078/apis/api-10022261-run"
    put:
      summary: モデルの登録/上書き
      deprecated: false
      description: ""
      tags:
        - private/voxel_model
      parameters:
        - name: id
          in: query
          description: ""
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: ""
          content:
            "*/*":
              schema:
                type: object
                properties: {}
                x-apidog-ignore-properties: []
                x-apidog-orders: []
          headers: {}
          x-apidog-name: 成功
      security:
        - bearer: []
      x-apidog-folder: private/voxel_model
      x-apidog-status: designing
      x-run-in-apidog: "https://app.apidog.com/web/project/663078/apis/api-10022291-run"
    delete:
      summary: モデルの削除
      deprecated: false
      description: ""
      tags:
        - private/voxel_model
      parameters:
        - name: id
          in: query
          description: ID番号
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: object
                properties: {}
                x-apidog-ignore-properties: []
                x-apidog-orders: []
          headers: {}
          x-apidog-name: 成功
      security:
        - bearer: []
      x-apidog-folder: private/voxel_model
      x-apidog-status: designing
      x-run-in-apidog: "https://app.apidog.com/web/project/663078/apis/api-10022292-run"
  /api/sensors:
    get:
      summary: 現在の情報を取得
      deprecated: false
      description: ""
      tags:
        - public/sensor
      parameters:
        - name: id
          in: query
          description: ID番号
          required: true
          schema:
            type: string
            format: uuid
        - name: data_limit
          in: query
          description: データの取得数
          required: false
          schema:
            type: integer
            default: 1
            format: int32
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: object
                properties:
                  sensor:
                    $ref: "#/components/schemas/Sensor"
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/SensorData"
                x-apidog-orders:
                  - sensor
                  - data
                required:
                  - sensor
                  - data
                x-apidog-ignore-properties: []
          headers: {}
          x-apidog-name: 成功
      security: []
      x-apidog-folder: public/sensor
      x-apidog-status: designing
      x-run-in-apidog: "https://app.apidog.com/web/project/663078/apis/api-10004197-run"
    put:
      summary: 一括登録/上書き
      deprecated: false
      description: ""
      tags:
        - private/sensor
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/Sensor"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: object
                properties: {}
                x-apidog-orders: []
                x-apidog-ignore-properties: []
          headers: {}
          x-apidog-name: 成功
      security:
        - bearer: []
      x-apidog-folder: private/sensor
      x-apidog-status: designing
      x-run-in-apidog: "https://app.apidog.com/web/project/663078/apis/api-10022287-run"
    delete:
      summary: 一括削除
      deprecated: false
      description: ""
      tags:
        - private/sensor
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
                format: uuid
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  format: uuid
          headers: {}
          x-apidog-name: 成功
      security:
        - bearer: []
      x-apidog-folder: private/sensor
      x-apidog-status: designing
      x-run-in-apidog: "https://app.apidog.com/web/project/663078/apis/api-10022288-run"
components:
  schemas:
    RiverNode:
      type: object
      properties:
        id:
          type: integer
          description: ZoomLv18でのヒルベルト値
          format: int64
        coord:
          $ref: "#/components/schemas/Coord3D"
      x-apidog-orders:
        - id
        - coord
      required:
        - id
        - coord
      x-apidog-ignore-properties: []
      x-apidog-folder: ""
    SensorData:
      type: object
      properties:
        value:
          type: number
          description: "測定値から平均処理をした値（水位ではない） [cm]"
          format: float
        battery_voltage:
          type: number
          description: "電池電圧の測定値 [mv]"
          format: float
        previous_sleep_time:
          type: integer
          description: "前回測定からのインターバル [分]"
          format: int64
        unix_time:
          type: integer
          description: UNIX時間
          format: int64
      x-apidog-orders:
        - value
        - battery_voltage
        - previous_sleep_time
        - unix_time
      required:
        - value
        - battery_voltage
        - previous_sleep_time
        - unix_time
      x-apidog-ignore-properties: []
      x-apidog-folder: ""
    NetworkStatus:
      type: object
      properties:
        system_mode:
          type: string
        operation_mode:
          type: string
        MCC:
          type: string
        MNC:
          type: string
        TAC:
          type: string
        SCelllD:
          type: string
        PCelllD:
          type: string
        frequency_band:
          type: string
        earfcn:
          type: string
        dlbw:
          type: string
        ulbw:
          type: string
        RSRQ:
          type: string
        RSRP:
          type: string
        RSSI:
          type: string
        RSSNR:
          type: string
      x-apidog-orders:
        - system_mode
        - operation_mode
        - MCC
        - MNC
        - TAC
        - SCelllD
        - PCelllD
        - frequency_band
        - earfcn
        - dlbw
        - ulbw
        - RSRQ
        - RSRP
        - RSSI
        - RSSNR
      required:
        - system_mode
        - operation_mode
        - MCC
        - MNC
        - TAC
        - SCelllD
        - PCelllD
        - frequency_band
        - earfcn
        - dlbw
        - ulbw
        - RSRQ
        - RSRP
        - RSSI
        - RSSNR
      x-apidog-ignore-properties: []
      x-apidog-folder: ""
    VoxelModel:
      type: object
      properties:
        name:
          type: string
        id:
          type: string
          format: uuid
        aabb:
          $ref: "#/components/schemas/LLAABB"
      x-apidog-orders:
        - name
        - id
        - aabb
      required:
        - name
        - id
        - aabb
      x-apidog-ignore-properties: []
      x-apidog-folder: ""
    LLAABB:
      type: object
      properties:
        top:
          type: number
          format: double
        bottom:
          type: number
          format: double
        right:
          type: number
          format: double
        left:
          type: number
          format: double
      x-apidog-orders:
        - top
        - bottom
        - right
        - left
      required:
        - top
        - bottom
        - left
        - right
      x-apidog-ignore-properties: []
      x-apidog-folder: ""
    Sensor:
      type: object
      properties:
        id:
          type: string
          description: ID番号
          format: uuid
        coord:
          $ref: "#/components/schemas/Coord3D"
        interval:
          type: integer
          minimum: 0.0
          format: int32
        scope:
          type: number
          format: float
          minimum: 0.0
      x-apidog-orders:
        - id
        - coord
        - interval
        - scope
      required:
        - id
        - coord
        - interval
        - scope
      x-apidog-ignore-properties: []
      x-apidog-folder: ""
    Coord3D:
      type: object
      properties:
        longitude:
          type: number
          format: double
          minimum: -180.0
          maximum: 180.0
        latitude:
          type: number
          format: double
          minimum: -90.0
          maximum: 90.0
        altitude:
          type: number
          format: float
      x-apidog-orders:
        - longitude
        - latitude
        - altitude
      required:
        - longitude
        - latitude
        - altitude
      x-apidog-ignore-properties: []
      x-apidog-folder: ""
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
servers: []